use_frameworks!

target 'TinyPlayerDemo' do
    workspace 'TinyPlayerDemo+Benchmark'
    project 'Demo/TinyPlayerDemo.xcodeproj'

    pod 'TinyPlayer', :path => '../'
end

target 'TinyPlayerTests' do
    workspace 'TinyPlayerDemo+Benchmark'
    project 'Demo/TinyPlayerDemo.xcodeproj'

    pod 'TinyPlayer', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble'
end

target 'TinyPlayerBenchmark' do
    workspace 'TinyPlayerDemo+Benchmark'
    project 'Benchmark/TinyPlayerBenchmark.xcodeproj'

    pod 'TinyPlayer', :path => '../'
end

target 'TinyPlayerTableViewDemo' do
    workspace 'TinyPlayerDemo+Benchmark'
    project 'TinyPlayerTableViewDemo/TinyPlayerTableViewDemo.xcodeproj'
    
    pod 'TinyPlayer', :path => '../'
end
